libc_a_SOURCES += \
  %D%/signal/kill.c \
  %D%/signal/sigaction.c \
  %D%/signal/sigprocmask.c \
  %D%/signal/sigtimedwait.c \
  %D%/stdio/rename.c \
  %D%/conf.c \
  %D%/dirent.c \
  %D%/env.c \
  %D%/fcntl.c \
  %D%/ldso.c \
  %D%/malloc.c \
  %D%/misc.c \
  %D%/mman.c \
  %D%/network.c \
  %D%/process.c \
  %D%/sbrk.c \
  %D%/sched.c \
  %D%/select.c \
  %D%/stat.c \
  %D%/time.c \
  %D%/unistd.c
