libc_a_SOURCES += \
  %D%/chown.c \
  %D%/clock_getres.c \
  %D%/clock_gettime.c \
  %D%/clock_nanosleep.c \
  %D%/clock_settime.c \
  %D%/close.c \
  %D%/environ.c \
  %D%/errno.c \
  %D%/execve.c \
  %D%/_exit.c \
  %D%/fork.c \
  %D%/fstat.c \
  %D%/getpagesize.c \
  %D%/getpid.c \
  %D%/gettod.c \
  %D%/isatty.c \
  %D%/kill.c \
  %D%/link.c \
  %D%/lseek.c \
  %D%/nanosleep.c \
  %D%/open.c \
  %D%/read.c \
  %D%/readlink.c \
  %D%/sbrk.c \
  %D%/sched.c \
  %D%/setitimer.c \
  %D%/signal.c \
  %D%/stat.c \
  %D%/symlink.c \
  %D%/sysconf.c \
  %D%/times.c \
  %D%/unlink.c \
  %D%/wait.c \
  %D%/write.c \
  %D%/context.S
  %D%/makecontext.c \
  %D%/inet_ntoa.c
